### ISSUE TITLE
Theme support

### ISSUE THREAD

**Issue by jeanCarloMachado** [dagraham/etm-tk#39]
It would be nice to have a theme support, for those how uses etm on the night is really painfull to see a white screen - in my case only with etm.

**Comment by dagraham** [comment]
Tkinter allows setting foreground and background colors for most 
widgets. As you note, since the background is primarily white, the etm 
color choices are primarily foreground and are set starting around line 
1842 in data.py:

# named colors: aliceblue antiquewhite aqua aquamarine azure beige
# bisque black blanchedalmond blue blueviolet brown burlywood
# cadetblue chartreuse chocolate coral cornflowerblue cornsilk crimson
# cyan darkblue darkcyan darkgoldenrod darkgray darkgreen darkgrey
# darkkhaki darkmagenta darkolivegreen darkorange darkorchid darkred
# darksalmon darkseagreen darkslateblue darkslategray darkslategrey
# darkturquoise darkviolet deeppink deepskyblue dimgray dimgrey
# dodgerblue firebrick floralwhite forestgreen fuchsia gainsboro
# ghostwhite gold goldenrod gray green greenyellow grey honeydew
# hotpink indianred indigo ivory khaki lavender lavenderblush
# lawngreen lemonchiffon lightblue lightcoral lightcyan
# lightgoldenrodyellow lightgray lightgreen lightgrey lightpink
# lightsalmon lightseagreen lightskyblue lightslategray lightslategrey
# lightsteelblue lightyellow lime limegreen linen magenta maroon
# mediumaquamarine mediumblue mediumorchid mediumpurple mediumseagreen
# mediumslateblue mediumspringgreen mediumturquoise mediumvioletred
# midnightblue mintcream mistyrose moccasin navajowhite navy oldlace
# olive olivedrab orange orangered orchid palegoldenrod palegreen
# paleturquoise palevioletred papayawhip peachpuff peru pink plum
# powderblue purple red rosybrown royalblue saddlebrown salmon
# sandybrown seagreen seashell sienna silver skyblue slateblue
# slategray slategrey snow springgreen steelblue tan teal thistle
# tomato transparent turquoise violet wheat white whitesmoke yellow
# yellowgreen

# type string to Sort Color Icon
tstr2SCI = {
     #   TStr  TNum Forground Color   Icon         view
     "ac": [23, "darkorchid", "action", "day"],
     "av": [16, "slateblue2", "task", "day"],
     "by": [19, "gold3", "beginby", "now"],
     "cs": [18, "slateblue2", "child", "day"],
     "cu": [22, "gray65", "child", "day"],
     "dl": [28, "gray70", "delete", "folder"],
     "ds": [17, "darkslategray", "delegated", "day"],
     "du": [21, "darkslategrey", "delegated", "day"],
     "ev": [12, "springgreen4", "event", "day"],
     "fn": [27, "gray70", "finished", "day"],

     "ib": [10, "firebrick3", "inbox", "now"],
     "ns": [24, "saddlebrown", "note", "day"],
     "nu": [25, "saddlebrown", "note", "day"],
     "oc": [11, "peachpuff4", "occasion", "day"],
     "pc": [15, "orangered", "child", "now"],

     "pu": [15, "firebrick3", "child", "now"],

     "pd": [14, "orangered", "delegated", "now"],
     "pt": [13, "orangered", "task", "now"],
     "rm": [12, "seagreen", "reminder", "day"],
     "so": [26, "slateblue1", "someday", "now"],
     "un": [20, "slateblue2", "task", "next"],
}

The trick in providing a dark theme would be 1) to choose a background 
color with 2) compatible foreground colors for the elements above.

Would you be willing to play around with this and give me your preferred 
colors? If so, I'll try to figure out a convenient way to override the 
defaults with colors imported, say, from a user provided 
"machado.colors" file.  A selection of such files could be added to the 
github site with perhaps a screenshot or two.

-Dan

**Comment by jeanCarloMachado** [comment]
I started working on a theme like your suggestion, but better now with an official dark theme. If I find necessary in the future I'll prepare a solarized dark theme. Thanks for all.

**Comment by dagraham** [comment]
The version now available on github has support for using "colors.cfg". 
There are also sample color files there: colors_dark.cfg and 
colors_light.cfg. I'm still working out some kinks but the basic 
framework is there.

-Dan

**Comment by dagraham** [comment]
There are also screen shots of the dark theme under images. I've fixed all the kinks I know about in 3.1.37. 

Send any color files you complete and I'll add them to github and post them on the etm home page.

Thanks for suggesting this.

-Dan
