### ISSUE TITLE
Problems with editing recurring tasks

### ISSUE THREAD

**Issue by therden** [dagraham/etm-tk#40]
**Scenario:**  editing either "This instance" or "This and all subsequent instances" of a recurring task which has prior @f and/or **@-** datetime values.

*Problem 1:*
While ETM discards datetime values associated with **@-** which precede "this instance", it then leaves that key in the item *even if no associated datetime values remain*.  Consequently, when the user tries to write/save their item, ETM then interprets the "**@-** [no datetime value]" as a reference to 12:00am on the current day and (unless that particular datetime value is generated by the repetition rule) produces an error message. 

*Fix 1:*  ETM should remove all **@-** datetime values which don't match the auto-edited recurring rule which it creates for "this" or "this and future" instances, and if no **@-** values remain then it should likewise remove the **@-** key.

*Problem 2:*
Unlike it's handling of @- datetime values, ETM does *not* discard @f datetime values which pre-date "this instance".  If the user doesn't manually remove them, when she tries to write/save the item ETM produces an error message.

*Fix 2:*  when ETM creates the new item representing "this instance" or "this and all subsequent instances", it should remove all @f datetime values which don't match the auto-edited recurring rule it creates, and if no @f values remain then it should likewise remove the @f key.

**Comment by dagraham** [comment]
Problem 1: I’ll implement the check for @- entries and remove the key when it is empty as you suggest.

Problem 2: This seems to me potentially to require changing both the recurrence rule and and the @f entry. 

Suppose, for example, that you have the recurring task:

	- weekly @s 2015-07-18 12am @f 20150724T1400;20150718T0000, 20150729T1500;20150725T0000 @r w

where the instance that was due on 7/18 was finished at 2pm on 7/24 and the instance that was due on 7/25 was finished at 3pm on 7/29. 

What result should obtain in the following cases when the user presses delete and selects "this and all subsequent instances"?

Case 1) The (unfinished) instance that is displayed on 8/8 is selected. 

Here it seems pretty obvious that the intent is to delete all repetitions on and after 8/8. This would result in the following modification

	- weekly @s 2015-07-18 12am @f 20150724T1400;20150718T0000, 20150729T1500;20150725T0000 @r w &u 2015-08-07 23:59:00

and, as expected, only three instances would remain: the two finished instances that display on 7/24 and 7/29 and the unfinished instance that displays on 8/1.

Case 2) The (unfinished) instance that is displayed on 8/1 is selected. 

Here too, the desired outcome seems pretty obvious - that all repetitions on and after 8/1 should be removed. The result would be

	- weekly @s 2015-07-18 12am @f 20150724T1400;20150718T0000, 20150729T1500;20150725T0000 @r w &u 2015-07-31 23:59:00 

As expected, only the finished instances that display on 7/24 and 7/29 would remain. The problem is that this item currently can no longer be edited and saved since etm will raise the error “No repetitions were generated”. I’m thinking that the correct behavior in this case would be for etm to remove the recurrence rule itself:

	- weekly @s 2015-07-18 12am @f 20150724T1400;20150718T0000, 20150729T1500;20150725T0000 

Do you agree?

Case 3) The finished instance that was due on 7/25 but is displayed on 7/29 is selected. This is a little less obvious but my guess is that the intent is to remove both the finished instance and all subsequent unfinished instances. If so, then etm needs to remove the recurrence rule and the relevant part of @f:

	- weekly @s 2015-07-18 12am @f 20150724T1400;20150718T0000

leaving only the single finished instance. Do you agree?

**Comment by therden** [comment]
Thank you for agreeing to have ETM remove the empty **@-** key.

I had been writing about Editing (not Deleting) "This" and "This and all subsequent" recurring items with prior @f values.  In those cases, ETM already changes the @s keyvalue; and I *think* it can leave the repetition rule alone (leaving it to the user to edit if she wants) so long as it drops the previous @f datetime values (and the @f key if it is empty.)

As for Deleting, I agree that, in addition to the @f key values the repetition rule will also need to be edited by adding or amending the &u key value pair.  In your second and third cases, it seems to me that, rather than removing the rule to dodge the error condition, ETM's error-checking code should be tweaked to allow the item to be saved, as the supposed Error is not true -- the unsaved item actually *does* generate repetitions (all of which just happen to have been Finished.)

**Comment by dagraham** [comment]
I'm hoping this is fixed in 3.1.47.

**Comment by therden** [comment]
Thank you -- I think we're almost there.  From my quick testing, the changes you've made seem to work for both Editing and Deleting, with one exception:  attempting to delete All Previous Instances results in ETM crashing and closing.

**Comment by dagraham** [comment]
Maybe ok in 3.1.53.

**Comment by therden** [comment]
v.py and version.py seem to have gotten borked -- maybe when you merged the remote-tracking branch?

Having cleaned them up, deleting All Previous Instanced does work correctly in 3.1.53.  Thank you again.

For future reference:  would you prefer that I Close issues I've opened and you've resolved, or do you prefer to do so?

**Comment by dagraham** [comment]
If you’re happy, please feel free to close the issue.

Thanks for spotting this and helping with the solution.

-Dan

On Jul 30, 2015, at 11:01 PM, therden <notifications@github.com<mailto:notifications@github.com>> wrote:


v.py and version.py seem to have gotten borked -- maybe when you merged the remote-tracking branch?

Having cleaned them up, deleting All Previous Instanced does work correctly in 3.1.53. Thank you again.

For future reference: would you prefer that I Close issues I've opened and you've resolved, or do you prefer to do so?

**Comment by therden** [comment]
You're welcome -- I consider it a privilege to contribute in my small way to etm.
