### ISSUE TITLE
Recent etm versions choking on Sample file data

### ISSUE THREAD

**Issue by therden** [dagraham/etm-tk#42]
ETM Version 3.2.7 and at least the version immediately preceding it are both ab-ending on startup.  

They're choking on the line in the sample.txt file with the value 

~ picked up lumber and paint @s +0 3p @e 1h15m @x 127.32 @t actions, sample

More specifically, etm seems to be having trouble with "1h15"

--- 2015-08-19 16:10:12,308 - ERROR - data.parse_period
    Invalid period string: '1h15'
Traceback (most recent call last):
  File "etm", line 83, in <module>
    view.main(dir=etmdir)
  File "C:\Users\50a597\MyApps\etmtk-latest\etmTk\view.py", line 4357, in main
    app = App()
  File "C:\Users\50a597\MyApps\etmtk-latest\etmTk\view.py", line 1057, in __init__
    self.updateClock()
  File "C:\Users\50a597\MyApps\etmtk-latest\etmTk\view.py", line 3550, in update Clock
    loop.loadData()
  File "C:\Users\50a597\MyApps\etmtk-latest\etmTk\data.py", line 6584, in loadData
    self.file2data = getViewData(bef, file2uuids, uuid2hash, self.options)
  File "C:\Users\50a597\MyApps\etmtk-latest\etmTk\data.py", line 5658, in getViewData
    getDataFromFile(f, file2data, bef, file2uuids, uuid2hash, options)
  File "C:\Users\50a597\MyApps\etmtk-latest\etmTk\data.py", line 5179, in getDataFromFile
    fmt_period(hsh['e'])
  File "C:\Users\50a597\MyApps\etmtk-latest\etmTk\data.py", line 1971, in fmt_period
    if td < oneminute * 0:
TypeError: unorderable types: str() < datetime.timedelta()

**Comment by dagraham** [comment]
I experience no problem with the entry you give with @e 1h15m. On the other hand, @e 1h15 raises an error. This is the way it is supposed to work. You can enter @e 75, @e 75m or @e 1h15m but not @e 1h15. If it’s an integer it’s interpreted as minutes, otherwise the m is required.

On Aug 19, 2015, at 4:12 PM, therden <notifications@github.com<mailto:notifications@github.com>> wrote:

~ picked up lumber and paint @s<https://github.com/s> +0 3p @e<https://github.com/e> 1h15m @x<https://github.com/x> 127.32 @t<https://github.com/t> actions, sample

**Comment by therden** [comment]
Hi Dan,

Hmmm...  when I moved the Sample file out of the data directory, the most recent version started up without a problem.

Ah hah! -- Looks like I misidentified the offending line.  Instead of 38, it must be line 85:

~ Activity (13)  @s 2 @e 1h15 @c context 2 @k client 1:project 2 @u agent 2

What's odd is that until very recently ETM was starting up despite this malformed line's appearance in the Sample file.  What's changed?

-Thomas

**Comment by dagraham** [comment]
God knows - look at the change history if you’re interested.

On Aug 19, 2015, at 4:53 PM, therden <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Dan,

Hmmm... when I moved the Sample file out of the data directory, the most recent version started up without a problem.

Ah hah! -- Looks like I misidentified the offending line. Instead of 38, it must be line 85:

~ Activity (13) @s<https://github.com/s> 2 @e<https://github.com/e> 1h15 @c context 2 @k<https://github.com/k> client 1:project 2 @u<https://github.com/u> agent 2

What's odd is that until very recently ETM was starting up despite this malformed line's appearance in the Sample file. What's changed?

-Thomas

**Comment by therden** [comment]
Okay...  In case you'd want to do edit it, the data file which, if present, will prevent the current version of *etmTk* from starting is linked to from your main *etmqt* page at http://people.duke.edu/~dgraham/etmqt.  

The URL for the sample data file is <http://people.duke.edu/~dgraham/etmqt/sample/sample_datafile.txt> .

-Thomas

**Comment by dagraham** [comment]
Thanks - I wondered where you had gotten the file. I've deleted it.
