### ISSUE TITLE
Crash upon startup - subsequent to python upgrade

### ISSUE THREAD

**Issue by stef204** [dagraham/etm-tk#47]
#### etm crashes with the following, after a recent python upgrade:

**% python --version**
Python 3.5.0

**% etm**
Traceback (most recent call last):
  File "/usr/bin/etm", line 9, in <module>
    from etmTk.data import setup_logging
ImportError: No module named 'etmTk'

Tried debuggin in gdb but on my system, python does not have debugging symbols enabled.

**(gdb) run etm**
Starting program: /usr/bin/python etm
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
/usr/bin/python: can't open file 'etm': [Errno 2] No such file or directory
[Inferior 1 (process 19894) exited with code 02]

**Comment by dagraham** [comment]
You need to reinstall etm using python3.5 so that it will be found in the 3.5 library. Also dateutils and PyYaml.

-Dan

On Oct 2, 2015, at 4:33 AM, stef204 <notifications@github.com<mailto:notifications@github.com>> wrote:


etm crashes with the following, after a recent python upgrade:

% python --version
Python 3.5.0

% etm
Traceback (most recent call last):
File "/usr/bin/etm", line 9, in
from etmTk.data import setup_logging
ImportError: No module named 'etmTk'

Tried debuggin in gdb but on my system, python does not have debugging symbols enabled.

(gdb) run etm
Starting program: /usr/bin/python etm
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
/usr/bin/python: can't open file 'etm': [Errno 2] No such file or directory
[Inferior 1 (process 19894) exited with code 02]

% python -m trace --count -C etm
Traceback (most recent call last):
File "/usr/lib/python3.5/runpy.py", line 170, in run_module_as_main
"__main_", mod_spec)
File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/usr/lib/python3.5/trace.py", line 856, in
main()
File "/usr/lib/python3.5/trace.py", line 785, in main
progname = prog_argv[0]
IndexError: list index out of range
