### ISSUE TITLE
&u until when start date but no time

### ISSUE THREAD

**Issue by melnospam** [dagraham/etm-tk#51]
Why, when doing on Oct 22, for the line:

    ^ Expect to see for Oct 21, not Oct 22 @s Oct 21 2015 @r d &u Oct 22 2015

python etmtk-3.2.16/etm $HOME/python/etm/mytest c  c ddd MMM dd yyyy -w60

gives:
    Wed Oct 21 2015
      ^ Expect to see for Oct 21, not Oct 22
    Thu Oct 22 2015
      ^ Expect to see for Oct 21, not Oct 22

Since the documentation says:

    &u: until  (datetime) Only include repetitions falling **before**

why do I see it for the "until" date (Oct 22)?

But note, for the line (adding a time "8pm" after the date):

  ^ Expect to see for Oct 21, not Oct 22 @s Oct 21 2015 8pm @r d &u Oct 22 2015

I get just what I expect (nothing for Oct 22):

    Wed Oct 21 2015
      ^ Expect to see for Oct 21, not Oct 22                       8:00pm

Am I missing something or is it a bug?

P.S. If I'm not sure whether it's a bug or not, should it go to
    github or the google dicsussion group?

**Comment by dagraham** [comment]
Well, I’m sorry to say the documentation is wrong. The implicit starting time for each repetition of your task is 12am. The &u entry also has an implicit time of 12am on 10/22. This entry for &u will allow repetitions with starting times on **or before** 12am. As you note, changing @s to any time after 12am will drop the repetition from the 22nd which now falls after the starting time. You mention 8pm but 12:01am would have the same effect.

This is also true for events so that an event

* test event @s 10/21 12am @e 1h @r d &u 10/22

would still appear on 10/22 because of the starting time.

I can’t remember when this behavior changed and I apologize for not correcting the documentation. The current behavior is consistent with iCalendar where the &u gets translated to UNTIL.

No need to file a bug - I’ll correct the documentation today.

-Dan

On Oct 22, 2015, at 2:03 PM, melnospam <notifications@github.com<mailto:notifications@github.com>> wrote:


Why, when doing on Oct 22, for the line:

^ Expect to see for Oct 21, not Oct 22 @s Oct 21 2015 @r d &u Oct 22 2015


python etmtk-3.2.16/etm $HOME/python/etm/mytest c c ddd MMM dd yyyy -w60

gives:
Wed Oct 21 2015
^ Expect to see for Oct 21, not Oct 22
Thu Oct 22 2015
^ Expect to see for Oct 21, not Oct 22

Since the documentation says:

&u: until  (datetime) Only include repetitions falling **before**


why do I see it for the "until" date (Oct 22)?

But note, for the line (adding a time "8pm" after the date):

^ Expect to see for Oct 21, not Oct 22 @s<https://github.com/s> Oct 21 2015 8pm @r<https://github.com/r> d &u Oct 22 2015

I get just what I expect (nothing for Oct 22):

Wed Oct 21 2015
  ^ Expect to see for Oct 21, not Oct 22                       8:00pm


Am I missing something or is it a bug?

P.S. If I'm not sure whether it's a bug or not, should it go to
github or the google dicsussion group?
