### ISSUE TITLE
Feature request: Alerts, reset based on actual time of snooze

### ISSUE THREAD

**Issue by stef204** [dagraham/etm-tk#53]
When snoozing an alert dialog for x minutes, it seems to snooze from original scheduled time (not desireable), as opposed to actual time of snooze (desireable).

IOW, one has an alert triggered at 2pm ("@a 0:m"), and snoozes it for 10 minutes, but lets more time go by than that value, e.g. 15 minutes, before addressing this pop-up.

The alert dialog box (the pop-up) which appeared at 2:10 PM stays on the screen with the 10 minutes snooze value "selected", waiting to be addressed (desireable/normal behavior).

If at that point--15 minutes from original time--one just clicks "Repeat" and leaves the same value of 10 minutes, the next Alert pops-up NOT 10 minutes from **that** (current) time--which it should--but 5 minutes based on the _last_ (past) snooze time,  This creates an undesireable offset which can cause the Alert to pop-up again, almost instantly in some cases, in any case much before the chosen snooze time (e.g. 10 minutes).  The user, whom is under the impression he/she just snoozed for 10 minutes, is presented with the Alert dialog at shorter intervals than 10 minutes, having to Snooze again, more times than necessary.  This is undesireable.

The Snooze value should reset from the time of the actual Snooze, so that if one snoozes for 15 minutes at 3:12 PM, NO further Alerts pops up until 3: 27 PM , no matter what.

**Comment by dagraham** [comment]
The snooze message clearly indicates the starting time for the additional period, e.g.,

    test snooze (now)
    9:30pm Today

    ----------------------------------------------------
                Repeat this alert?
    This is the last alert scheduled for this item. To repeat it,
    enter the number of minutes after 9:30pm for the repetition.

This is designed, like an alarm clock, so that the snooze applies to the original alarm time, not the time that the user gets around to setting the snooze which, with an alarm clock would presumably be fairly soon.  It would, of course, be possible to change the behavior so that the additional period starts from the time that the snooze is activated but then the wording would have to be changed to something like

enter the number of minutes from the current time for the repetition.

Is this the behavior you would like?

**Comment by stef204** [comment]
Yes, absolutely.  It would make the most sense and be most logical.

**Comment by stef204** [comment]
Still have a problem with this.
The dialog should really say (and do), IMO:

> To repeat it,
> enter the number of minutes from now for the repetition.

The value of "now" should be whatever time at which I press "repeat" with whatever "snooze" value chosen.

As it stands now, the behavior is the same as before, it pops up again based on last pop-up tim instead of based on when I click "snooze:.

Again, whenever one clicks snooze for x minutes, is when the next countdown should start so that one expects and gets a new alert exactly as he/she has chosen: x minutes from time of snooze.
I think thew

**Comment by dagraham** [comment]
This is not how it works for me. When this alert triggered


test (now)
1:56pm Today

-----------------------------------------------------------
                Repeat this alert?
This is the last alert scheduled for this item. To repeat
it, enter the number of minutes to wait for the repetition.


I waited until 1:58pm, entered 2 minutes and pressed return. The snooze was set for 2pm and triggered at that time as it should.  Are you using the updated version?

-Dan


On Nov 6, 2015, at 1:48 PM, stef204 <notifications@github.com<mailto:notifications@github.com>> wrote:


Still have a problem with this.
The dialog should really say (and do), IMO:

To repeat it,
enter the number of minutes from now for the repetition.

The value of "now" should be whatever time at which I press "repeat" with whatever "snooze" value chosen.

As it stands now, the behavior is the same as before, it pops up again based on last pop-up tim instead of based on when I click "snooze:.

Again, whenever one clicks snooze for x minutes, is when the next countdown should start so that one expects and gets a new alert exactly as he/she has chosen: x minutes from time of snooze.
I think thew

**Comment by stef204** [comment]
I tested it as you did.  I first snoozed for 2 minutes, when alert pop-up I let 1 minute go by and snoozed for 2 minutes, and alert poped up again after 1 minute.
The test case is letting time go by before snoozing again.....
Unless I did a rest and am inagining things, but I don't think I am (not yet at least.)
I am using the git version. 
Did you push all the changes?

**Comment by dagraham** [comment]
Here’s the log of my last test:

4:10 alert (last) triggered
4:25 pressed snooze with 7 minutes
4:32 alert (snooze) triggered
4:56 pressed snooze with 7 minutes
5:03 alert (snooze) triggered
5:06 pressed snooze with 7 minutes
5:13 alert (snooze) triggered

Isn’t this exactly the behavior you wanted?

I’ve updated the version number on git to 3.2.21 and changed the wording to the version you favored:

-----------------------------------------------------------
                    Repeat this alert?
This is the last alert scheduled for this item. To repeat it,
  enter the number of minutes from now for the repetition.

-Dan

On Nov 6, 2015, at 2:51 PM, stef204 <notifications@github.com<mailto:notifications@github.com>> wrote:


I tested it as you did. I first snoozed for 2 minutes, when alert pop-up I let 1 minute go by and snoozed for 2 minutes, and alert poped up again after 1 minute.
The test case is letting time go by before snoozing again.....
Unless I did a rest and am inagining things, but I don't think I am (not yet at least.)
I am using the git version.
Did you push all the changes?

**Comment by stef204** [comment]
OK, will test again on my sidee and post back here.  Thanks.

**Comment by stef204** [comment]
OK, the feature change was *no*t being picked up by my install, for some reaon, I've had some trouble with python install.
So I uninstalled everything, and then ran it locally after a git pull and it is working fine, as you described.
Sorry for this problem with python setup on my side.
Can you please also push version 3.2.21 to: http://people.duke.edu/~dgraham/etmtk/  ?
And thanks a lot for being responsive and this new feature.

**Comment by dagraham** [comment]
etm.1 and CHANGES are part of the python distribution but were missing from the git repository. I've added them.  Please let me know if install is still causing problems.

**Comment by stef204** [comment]
Dan,
We are all set.  Everything seems to be in order.
Thank you again for being responsive and open to requests, most appreciated.
