### ISSUE TITLE
Option to use different file extension

### ISSUE THREAD

**Issue by cipharius** [dagraham/etm-tk#68]
Currently the etm data extension is generic `.txt` file. Since it's so widely used file extension, etm picks up random unrelated support files as inbox notes.

With the ability to set custom file extension for data files, it would be possible for such workflow, where a `projects` data directory could be used both for storing directories of projects with etm data and also for keeping support material in the same project directories (which will most likely contain some unrelated `.txt` files).

**Comment by dagraham** [comment]
Etm itself does not put any .txt support files in it’s data directory. What is the source of these support files?

-- Dan
On Sep 30, 2019, 12:37 AM -0400, Valts Liepiņš <notifications@github.com>, wrote:

Currently the etm data extension is generic .txt file. Since it's so widely used file extension, etm picks up random unrelated support files as inbox notes.

With the ability to set custom file extension for data files, it would be possible for such workflow, where a projects data directory could be used both for storing directories of projects with etm data and also for keeping support material in the same project directories (which will most likely contain some unrelated .txt files).

**Comment by cipharius** [comment]
I wished to have etm data directory to function both as event and task collection and storage for project (as defined in Getting Things Done) related files.

Now that I look at it, perhaps it would be wiser to keep reference files separated from etm data. I will give that a go and report back here.

So far I have been reading the included documentation files, but it's not clear what kind of workflows and filesystem structures work well with etm. Are there any resources that describe some existing etm workflows?

**Comment by dagraham** [comment]
Since etm is forever searching it’s data directory for item files, putting other files in there is probably not a good idea.

On the other hand, etm items can have @g “goto” links where the goto entry is either a url or a file path. When an item is selected with a goto link, pressing G will use the operating system to “open” the link using the system default application. On my mac, the system default for a url would be to use Safari to open the link. For a text file path, it would be to open the file using vim (my default for text files). For a path to a directory, it would be to open a window in Finder (the default file browser) on the directory. And so forth.  Maybe this would help with your work flow?

-- Dan
On Sep 30, 2019, 9:04 AM -0400, Valts Liepiņš <notifications@github.com>, wrote:

I wished to have etm data directory to function both as event and task collection and storage for project (as defined in Getting Things Done) related files.

Now that I look at it, perhaps it would be wiser to keep reference files separated from etm data. I will give that a go and report back here.

So far I have been reading the included documentation files, but it's not clear what kind of workflows and filesystem structures work well with etm. Are there any resources that describe some existing etm workflows?
