### ISSUE TITLE
iCalendar export lacks DTSTAMP field and VTIMEZONE entry

### ISSUE THREAD

**Issue by cipharius** [dagraham/etm-tk#69]
I ran into issue, where my web calendar (SOGo Calendar) wouldn't interpret timezone information attached to the exported VEVENTS.

After running the etm generated ics file through [iCalendar validator](https://icalendar.org/validator.html) two issues were detected: undefined timezone identifiers and missing DTSTAMP fields.

Manually adding VTIMEZONE definition fixed the issue with my web calendar not interpreting the DateTimes correctly.

Although my particular issue wasn't due to missing DTSTAMP, it still might be a good idea to define it as it's a mandatory VEVENT field.

**Edit:** *(this edit now seems irrelevant compared to edit2)* After checking out how SOGo acquires VTIMEZONE definitions, I found a [file with instructions](https://github.com/inverse-inc/sogo/blob/master/SOPE/NGCards/TimeZones/UPDATING) on how standard timezone definitions can be converted to iCal compatible format.

**Edit2:** After some research on how currently etm iCal export works, I found [a compatible potential solution for generating VTIMEZONE entries](https://djangosnippets.org/snippets/10569/).

**Comment by dagraham** [comment]
Thanks for your feedback. A starting time, and thus a dtstamp, is required for some etm items but not for all. For example, events require a starting time but tasks do not. What type of item did your validator flag for a missing DTSTAMP field?

-- Dan
On Sep 30, 2019, 2:10 AM -0400, Valts Liepiņš <notifications@github.com>, wrote:

I ran into issue, where my web calendar (SOGo Calendar) wouldn't interpret timezone information attached to the exported VEVENTS.

After running the etm generated ics file through iCalendar validator<https://urldefense.proofpoint.com/v2/url?u=https-3A__icalendar.org_validator.html&d=DwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=cjSGCFDvj7Zy-plAeyNJjDIBRBeNSNbZaJLNyuBRtxo&m=WTaWSERNTqQSIyOBdTwL5jXVe_ChMVzBDor4GWXosss&s=wVn4k57BQUym1ctEx3nuJSxLWqBts3CMb5q65tGoW7Q&e=> two issues were detected: undefined timezone identifiers and missing DTSTAMP fields.

Manually adding VTIMEZONE definition fixed the issue with my web calendar not interpreting the DateTimes correctly.

Although my particular issue wasn't due to missing DTSTAMP, it still might be a good idea to define it as it's a mandatory VEVENT field.

**Comment by cipharius** [comment]
All the VEVENTS I had in the file were for events, so with both DTSTART and DTEND.

I have not studied iCalendar specification, so I am not aware what DTSTAMP is required for, my main issue is with VTIMEZONE definition.

**Comment by dagraham** [comment]
Out of curiosity, what is your timezone?

-- Dan
On Sep 30, 2019, 8:52 AM -0400, Valts Liepiņš <notifications@github.com>, wrote:

All the VEVENTS I had in the file were for events, so with both DTSTART and DTEND.

I have not studied iCalendar specification, so I am not aware what DTSTAMP is required for, my main issue is with VTIMEZONE definition.

**Comment by cipharius** [comment]
My timezone is Europe/Riga and I have explicitly set it as `local_timezone` in configuration.

Strangely enough, when I manually import the etm ics in SOGo web calendar, it displays events 3 hours later, while when the ics file is synced using vdirsyncer, the same web calendar show that events are 3 hours earlier.

Also I noticed that when I sync the etm generated ics file (from `icssync_folder`) with my calendar server using `vdirsyncer`, it deletes and recreates all events, even when they weren't changed.
